### ISSUE TITLE
rsa_plain.py key generation error

### ISSUE THREAD

**Issue by mehfluffy** [fbv81bp/Montgomery_multiplication#1]
The computation of _d_ does not seem to be correct.

https://github.com/feketebv/Montgomery_multiplication/blob/1032ecb0d73e8af48d662d328231f784b6d8fde2/rsa_plain.py#L6

**Comment by fbv81bp** [comment]
Thanx. That is not the Euler's totient, I may have accidentially choosen lucky numbers.
